package practisetest_II;

public class MethodAndEncapsulation {
	public static void main(String []arr) {
//	new MethodAndEncapsulation().meth();//here main method is the caller method which is not handling Exception thrown by its calling method meth().so compiler error
	}
	public void meth() throws Exception{
		for(int x=0;x>5;x++) {
			System.out.println(x);
		}
	}

}
